# Generated by Django 5.1.5 on 2025-03-29 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("tel_number", models.CharField(max_length=20)),
                (
                    "company_tel_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("company_address", models.TextField()),
                ("event_explanation", models.TextField()),
                (
                    "event_dates",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ExhibitionQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("tel_number", models.CharField(max_length=20)),
                (
                    "office_tel_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("interest_show", models.CharField(max_length=200)),
                ("dates", models.CharField(blank=True, max_length=100, null=True)),
                ("booth_requirements", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
