# Generated by Django 5.1.5 on 2025-02-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CorporateSerices",
            new_name="CorporateServices",
        ),
        migrations.CreateModel(
            name="CorporateServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="corporate/")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.corporateservices",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="ExhibitionSerices",
            new_name="EventServices",
        ),
        migrations.CreateModel(
            name="EventServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="event/")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.eventservices",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="SocialSerices",
            new_name="ExhibitionServices",
        ),
        migrations.CreateModel(
            name="ExhibitionServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="exhibition/")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.exhibitionservices",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="EventSerices",
            new_name="SocialServices",
        ),
        migrations.CreateModel(
            name="SocialServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="social/")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.socialservices",
                    ),
                ),
            ],
        ),
    ]
