# Generated by Django 5.1.5 on 2025-02-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_corporateserviceimage_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("paragraph", models.CharField(max_length=200)),
            ],
        ),
    ]
