# Generated by Django 5.1.5 on 2025-02-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("review", models.TextField()),
            ],
        ),
    ]
