# Generated by Django 5.0.6 on 2024-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='signing_reason',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='split_large_files',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='url',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='visible_signature',
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('signing_reason', models.CharField(max_length=255)),
                ('visible_signature', models.BooleanField(default=False)),
                ('split_large_files', models.BooleanField(default=False)),
                ('files', models.ManyToManyField(to='core.uploadedfile')),
            ],
        ),
    ]
