# Generated by Django 5.0.6 on 2024-05-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedfile_signed_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadbatch',
            name='files',
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='files',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.uploadedfile'),
            preserve_default=False,
        ),
    ]
