# Generated by Django 5.0.6 on 2024-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('url', models.URLField(blank=True, null=True)),
                ('signing_reason', models.CharField(max_length=255)),
                ('visible_signature', models.BooleanField(default=False)),
                ('split_large_files', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
