# Generated by Django 5.0.6 on 2024-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_uploadedfile_signing_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='signed_uploads/'),
        ),
    ]
