# Generated by Django 5.0.6 on 2024-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_uploadbatch_files_uploadbatch_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadbatch',
            name='files',
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='files',
            field=models.ManyToManyField(to='core.uploadedfile'),
        ),
    ]
